# Site settings
title: A odisseia do puto
description: "Engenharia de software, cultura pop e caos. O hub definitivo para quem sobrevive a war rooms â€” sem onanismo intelectual."
date_format: "%d/%m/%Y"
url: ""
permalink: pretty
exclude: ["README.md", ".gitignore"]

# Build settings
markdown: kramdown
paginate: 50
highlighter: rouge
plugins: [jekyll-paginate, jekyll-feed]
